spring:
  application:
    name: merchant-payments
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info
payments:
  payment-requests:
    expiry:
      min: 5m
      max: 30d
      default-ttl: 24h
springdoc:
  override-with-generic-response: false